language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

before_install:
    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy,scipy numpy scipy

install: 
    - pip install .

script:
    - travis_wait 30 admix -m K7b E11 K36 K47

notifications:
    email: false
